version: "3"
services:
  cospirit-front-component:
    image: cospirit/node:10.11
    container_name: cospirit-front-component
    restart: "no"
    working_dir: /srv/cospirit-front-component
    hostname: cospirit-front-component
    tty: true
    networks:
      - public
    volumes:
      - ./:/srv/cospirit-front-component
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    ports:
      - 80
    labels:
      - "traefik.backend=app-cospirit-front-component"
      - "traefik.frontend.rule=Host:cospirit-front-component.localhost"
      - "traefik.docker.network=public"
networks:
  public:
    external: true
