version: "3.8"

services:
  app:
    image: cospirit/node:10.11
    container_name: front-component_app
    restart: "no"
    working_dir: /srv/app

    tty: true
    labels:
      - "traefik.enable=false"
    volumes:
      - ./:/srv/app
